# Generated by Django 5.2.3 on 2025-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='count_post',
            field=models.IntegerField(default=0),
        ),
    ]
