# Generated by Django 5.2.3 on 2025-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_appuser_count_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='picture',
            field=models.URLField(default='http://linkpict.com'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='picture',
            field=models.URLField(default='http://linkpict.com'),
        ),
    ]
