# Generated by Django 5.2.3 on 2025-06-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_administrator_picture_appuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='picture',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='picture',
            field=models.URLField(),
        ),
    ]
