# Generated by Django 5.2.3 on 2025-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='linkImg',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='receipes',
            field=models.TextField(),
        ),
    ]
